# Generated by Django 5.1.4 on 2024-12-13 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=1024)),
                ('user_name', models.CharField(max_length=1024)),
                ('user_surname', models.CharField(max_length=1024)),
                ('active_ads', models.IntegerField(null=True)),
                ('tel_num', models.CharField(blank=True, max_length=1024, null=True)),
                ('store_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('email', models.CharField(max_length=1024)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=8)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=1024, null=True)),
                ('location', models.CharField(blank=True, max_length=1024, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='merkatapp.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='merkatapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=1024)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='merkatapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute_id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=1024)),
                ('attribute_value', models.CharField(max_length=1024)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='merkatapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=1024)),
                ('store_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='merkatapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sent_at', models.DateField()),
                ('status', models.CharField(blank=True, max_length=1024, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='received_messages', to='merkatapp.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sent_messages', to='merkatapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='SellerInStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='merkatapp.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='merkatapp.user')),
            ],
            options={
                'unique_together': {('user', 'store')},
            },
        ),
    ]
