# Generated by Django 5.1.4 on 2024-12-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merkatapp', '0002_alter_user_created_at_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattributes',
            name='attribute_value',
            field=models.CharField(default='Unknown', max_length=1024),
        ),
        migrations.AddField(
            model_name='subcategoryattributes',
            name='subattribute_value',
            field=models.CharField(default='Unknown', max_length=1024),
        ),
    ]
