# Generated by Django 5.1.4 on 2024-12-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merkatapp', '0005_listingattributevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
