# Generated by Django 5.1.4 on 2025-01-10 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merkatapp', '0006_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='media/listings_images/default_listing.jpg', null=True, upload_to='listings_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='images', to='merkatapp.listing'),
        ),
    ]
