# Generated by Django 5.1.4 on 2025-01-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merkatapp', '0009_chatroom_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
